### ISSUE TITLE
Change color of Anchor to "brand"?

### ISSUE THREAD

**Issue by johnliu55tw** [grommet/grommet-theme-hpe#123]
Currently the color of an Anchor is "text", which is black by default. This makes it hard to tell that it's a clickable link. I think changing it to "brand" which is HPE green will signify that it's clickable. Any thoughts?

![image](https://user-images.githubusercontent.com/5047724/95962868-84457000-0e39-11eb-9577-90342d6ca653.png)

![image](https://user-images.githubusercontent.com/5047724/95962899-91faf580-0e39-11eb-9b90-f0a79bdfac84.png)

I think I can send a PR for this color is desired.

**Comment by MikeWalrath** [comment]
@johnliu55tw apologies for the delay! 

The update to Anchor was made to simplify the use case for Anchor and also to clarify the separation between Anchor and Button.

Working in collaboration with the Brand organization we felt that the difference is text weight along with the underline gave Anchor enough visual difference to show it was still clickable without competing with the primary call to action. 

For more rational and guidance please take a look at the below references. 
https://design-system.hpe.design/components/anchor
https://design-system.hpe.design/templates/forms
https://design-system.hpe.design/components/button

Ill keep the issue open if you have any additional questions. Also feel free to reach out to me if you would like to chat about it more.

**Comment by ShimiSun** [comment]
Adding to @MikeWalrath 👆 
And also to answer your concern: 
> This makes it hard to tell that it's a clickable link.

To make it clear that Anchor is indeed an interactive element (i.e. clickable), the Anchor now has the underline styling and the cursor is changing on hover, it is compliant with accessibility standards and addresses your concern.

**Comment by johnliu55tw** [comment]
@MikeWalrath no problem. I didn't know the newer version has added an underline to the Anchor component. I think that solves my problem here :+1: This issue can be closed.
