### ISSUE TITLE
evaluate rounded end caps for icons

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet-theme-hpe#124]
The CCS designs call for SVG paths to have round end caps. See if we can make a generic change in the HPE theme that will work across all icons. I suspect some icons might need their paths to be adjusted to work with this. This issue is just to see what's possible.

**Comment by halocline** [comment]
Created a [demo branch](https://deploy-preview-1217--keen-mayer-a86c8b.netlify.app/foundation/icons#rounded-linecap-audit) to show stroke-linecap = round applied to Grommet icons.

**Comment by ericsoderberghp** [comment]
Thanks for publishing this, very helpful.

From my quick scan,

- there are some that work well, such as Add
- there are some that don’t seem to have any effect, such as Action
- and there are some that seem to have problems, such as Actions

It would be interesting to see how many we have in each of those buckets, and then see what it would take to correct as needed, just to scope the effort.

**Comment by halocline** [comment]
> It would be interesting to see how many we have in each of those buckets, and then see what it would take to correct as needed, just to scope the effort.

I'd be happy to quantify and summarize by "bucket" as a next step.

**Comment by ericsoderberghp** [comment]
Your choice whether that should be a separate issue in the backlog or a continuation of this one.

**Comment by halocline** [comment]
Closing this and opening https://github.com/grommet/grommet-theme-hpe/issues/135 as next phase.
