### ISSUE TITLE
FormField validation message icon

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-theme-hpe#126]
The Figma designs show a circle information icon on validation messages. This should be in the HPE theme.

Add the icon to the theme.

Also, change grommet to handle both component and element values. For example, `menu.icons.down: FormDown` as well as `icon: <MyCustomIcon with props />`.

**Comment by taysea** [comment]
Context on a grommet PR that should allow for theming of the form icon: https://github.com/grommet/grommet/pull/4473

I think I dropped the ball here of refactoring the site examples/applying this to the theme. I will work on this here.

**Comment by halocline** [comment]
@taysea FYI, this should be unblocked now. grommet-theme-hpe now supports JSX.

**Comment by taysea** [comment]
Thanks, I will publish a PR this afternoon!
