### ISSUE TITLE
MS-Edge Colors does not support 8-digit hex values

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet-theme-hpe#132]
I'm not sure what the official line is with MS-Edge support.  The most recent version is Chromium based and should be fine.  The version immediately prior to the Chromium release is:

Microsoft Edge 44.19041.1.0
Microsoft EdgeHTML 18.19041

grommet-theme-hpe uses 8-digit hex values to represent colors with alpha channel.  MS-Edge (pre-Chromium) does not support that.

E.g. in `grommet-theme-hpe`, the color `background-contrast` decodes to `#11111108`.  Using color `background="background-contrast"` does not work on MS-Edge.

Instead it needs something like:

`background={{ color: '#111111', opacity: '0.03' }}` 

Since `"background-contrast"` is deep in the `grommet-theme-hpe`, it could be changed there, presumably.

PS: Thanks to Shimi for her insight into this issue.

**Comment by taysea** [comment]
@ericsoderberghp I'm proposing we close this issue since Microsoft has stopped support of pre-chromium Edge in April 2021. If you agree, can you close?

**Comment by taysea** [comment]
Closing based on the above comment.
