### ISSUE TITLE
Implement button sizes in Theme

### ISSUE THREAD

**Issue by halocline** [grommet/grommet-theme-hpe#139]
This follows on the work completed in https://github.com/grommet/hpe-design-system/issues/1205

[Figma](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=1842%3A0)

- [ ] Snapshot before theme changes
- [ ] Add changes to theme
- [ ] Snapshot after theme changes

**Comment by halocline** [comment]
Objective: To be able to specify a size for a button and have it scale according to [Figma](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=1842%3A0)

Findings:
- Adjusting button's theme properties do not seem to have the desired effect
Applied
```
button: {
    size: {
      small: {
        border: {
          radius: '4px',
        },
        pad: {
          vertical: '4px',
          horizontal: '8px',
        },
      },
      medium: {
        border: {
          radius: '4px',
        },
        pad: {
          vertical: '6px',
          horizontal: '12px',
        },
      },
      large: {
        border: {
          radius: '6px',
        },
        pad: {
          vertical: '8px',
          horizontal: '16px',
        },
      },
      xlarge: {
        border: {
          radius: '8px',
        },
        pad: {
          vertical: '12px',
          horizontal: '24px',
        },
      },
    },
```
but get:
![Screen Shot 2020-11-10 at 11 27 18 AM](https://user-images.githubusercontent.com/1756948/98715765-d057d780-2347-11eb-85af-4c8dd4eaefcc.png)

- Cause is due to the order in which the styles are being built up in `StyledButtonKind`, where padding values are set and then trumped later in subsequent styles being applied 
![Screen Shot 2020-11-10 at 11 31 06 AM](https://user-images.githubusercontent.com/1756948/98717058-cb942300-2349-11eb-8481-142446e84a50.png)

- Can re-visit the order in which padding and border-radii are applied which gets us closer
![Screen Shot 2020-11-10 at 11 59 05 AM](https://user-images.githubusercontent.com/1756948/98718851-35adc780-234c-11eb-84c4-8ea1406013b1.png)

, however, we will run into the following issues:
  - Size assumes consistent padding/border-radius across Kinds, however, Kinds may have different definitions (e.g. [primary](https://github.com/grommet/grommet-theme-hpe/blob/4cf0cef5967b309cdb0e704f98c58fe77a415fd7/src/js/index.js#L297) & [secondary](https://github.com/grommet/grommet-theme-hpe/blob/4cf0cef5967b309cdb0e704f98c58fe77a415fd7/src/js/index.js#L311))
  - Styling of button states is also problematic as padding and border are also adjusted at various states (e.g. [secondary hover](https://github.com/grommet/grommet-theme-hpe/blob/4cf0cef5967b309cdb0e704f98c58fe77a415fd7/src/js/index.js#L384))

Because of these issues, working within the existing architecture, it seems like we will need to add a `size` property to each Kind definition and each State+Kind definition.

- Varying `gap` between label and icon and various sizes. This concept does not yet exist.

- Scaling icon size proportional to label line-height. This concept does not yet exist.


@ericsoderberghp, @ShimiSun, @taysea - I think it would be worthwhile to get together to discuss these findings and approaches prior to any further work.
CC: @MikeWalrath, @gregfuruiye

**Comment by ericsoderberghp** [comment]
Let's use this issue to track the grommet exploration/ideation work as well for now.

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/grommet/issues/4754
