### ISSUE TITLE
Tabs highlighting isn't prominent enough for the users to identify which tab is selected.

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet-theme-hpe#146]
- [ ] Ideate a few other approaches
- [ ] run some A/B UserZoom tests

**Comment by ericsoderberghp** [comment]
Related to https://github.com/grommet/hpe-design-system/issues/779

**Comment by rajasekar-ramasamy** [comment]
@ericsoderberghp here's the link from Edgar for Tabs 

https://designer.grommet.io/menu?id=Tabbed-pages-edgar-circenis-hpe-com
