### ISSUE TITLE
Sidebar Button styling is "too loud"

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet-theme-hpe#147]
FYI, this was first entered in Slack: https://grommet.slack.com/archives/C04LMJWQT/p1607551560217200

For emphasis, this is not about individual buttons placed around a page, but rather just a long list of buttons, as they appear in the sidebar.

I have attached two sidebar images; the first uses plain buttons, the 2nd one uses the HPE theme.

I feel the collection of HPE themed buttons causes the  sidebar to have too much visual-weight compared to the content of the page.  i.e. the sidebar has become distracting, demanding attention from my eye.

I  understand this is the difference between WCAG AAA pass/fail.  While WCAG rating for text contrast is important, I feel it is augmented by icon usage, which reduces the reliance on text alone.

Can we 'soften' the buttons in a sidebar and still achieve a good balance with WCAG text-contrast ratings?

## Subtle Sidebar (Plain Buttons)

Text contrast ratio does not pass WCAG AA.

![sidebar-quiet](https://user-images.githubusercontent.com/8231064/101829930-83059a80-3b7f-11eb-973b-e439864b9634.png)

## Loud Sidebar (HPE themed Buttons)

Text cotnrast is WCAG AAA rated, though I feel it has become too loud, compared to the page content.

![sidebar-loud](https://user-images.githubusercontent.com/8231064/101829949-8bf66c00-3b7f-11eb-80a3-f31e1390e03f.png)

**Comment by ericsoderberghp** [comment]
Aren't using Sidebar for navigation as shown here any more
