### ISSUE TITLE
Selected Tab is barely distinguishable from other Tabs

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet-theme-hpe#15]
HPE theme 1.0.2.

See my codesandbox for an example: https://codesandbox.io/s/toggle-theme-tabs-1mb7s

---

### HPE Theme
![image](https://user-images.githubusercontent.com/8231064/76047041-4e8bff00-5fad-11ea-823f-9cede77bda15.png)

---

### Default Grommet Theme
![image](https://user-images.githubusercontent.com/8231064/76047083-74190880-5fad-11ea-9abe-ee004859ad2d.png)

**Comment by ShimiSun** [comment]
How is it recommended to be done on the sticker-sheet? do we have a design idea how it should look?

**Comment by LiveFreeAndRoam** [comment]
Sorry, I'm not sure what you are referring to when you mention "sticker-sheet".

From the point-of-view of contrast between selected-tab and unselected-tabs, I suggest the minimum mandatory requirement ought to be a WCAG 2.1, AA standard for both "light" and "dark" themes.

Issue #4 is related.  Ideally, when there are just two tabs, the selected tab ought to be further differentiated with a separate element (e.g. a dot prefix) or highlighted in some other way that clearly identifies it as selected, compared to the 'other' tab.

**Comment by gregfuruiye** [comment]
We are conducting a color study currently to help address the use of text colors to meet all WCAG 2.1 AA standards for both dark and light modes. Our hope is to complete that study this week with design work published by April 3 and released in the theme following shortly.

**Comment by LiveFreeAndRoam** [comment]
I fear my point may have been misunderstood.

I checked the grommet-theme-hpe 1.0.5.  The selected Tab is black, #000000.  The inactive Tabs are colored with #666666, (text-xweak).  The color contrast between selected and unselected tabs is just [3.65](https://contrast-ratio.com/#%23666666-on-%23000000).  The difference between these are difficult to observe.

**Comment by gregfuruiye** [comment]
@LiveFreeAndRoam, I agree that the difference between selected and unselected tabs is difficult to observe. Each component is being re-evaluated, including tabs. Interestingly enough, the contrast ratio of 3.65 is enough to meet [WCAG 2.1 compliance](https://www.w3.org/WAI/WCAG21/Techniques/general/G183). However, to your point, we can do better and tabs is one component that is currently undergoing changes to address [distinguishable use of color.](https://www.w3.org/WAI/WCAG21/Understanding/use-of-color).

**Comment by taysea** [comment]
Closing this ticket, in v5 the active tab is clearly distinguished from non-active tabs: https://design-system.hpe.design/components/tabs?q=tabs
