### ISSUE TITLE
Focus indicator broken for checkbox

### ISSUE THREAD

**Issue by bdesouza** [grommet/grommet-theme-hpe#151]
It looks like the focus indicator for checkbox is broken on the hpe theme. It seems like it's been broken in the previous release as well.

Grommet
<img width="64" alt="Screen Shot 2021-01-11 at 8 28 26 PM" src="https://user-images.githubusercontent.com/664555/104269764-e53a0f80-544b-11eb-9fcc-0a51754092c9.png">

Grommet + HPE Theme
<img width="65" alt="Screen Shot 2021-01-11 at 8 29 51 PM" src="https://user-images.githubusercontent.com/664555/104269773-e703d300-544b-11eb-9930-ec2301e6e325.png">

**Comment by halocline** [comment]
**Summary**
- The checkbox focus is being suppressed by grommet-theme-hpe here: https://github.com/grommet/grommet-theme-hpe/blob/8f38d1575ab6e2b7d6af3ea55bf47412c43fe276/src/js/index.js#L482
- The historic rationale for this originated on the design direction was based on this [Figma](https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/HPE-Checkbox-Component?node-id=1388%3A77). This direction calls for focus to be applied to the surrounding FormField and not on the specific checkbox input. However, this did not account for checkboxes used outside of a FormField context.
![Screen Shot 2021-01-28 at 2 34 31 PM](https://user-images.githubusercontent.com/1756948/106202015-8d531680-6176-11eb-8c34-45a59d821b74.png)
- Need to account for focus on a checkbox in and out of a FormField context.

**Comment by halocline** [comment]
Looking for feedback on potential approaches:
- [Approach 1](https://github.com/grommet/grommet/pull/4910)
- [Approach 2](https://github.com/grommet/grommet/pull/4911)
- Other ideas?

**Comment by ericsoderberghp** [comment]
Another idea ...
which I think is based on how FormField + TextInput work ...
is to do this via an explicit property.
FormField and TextInput use `plain`.
So, we could have FormField do what it does at line 191 in a way that effects a contained CheckBox.

**Comment by halocline** [comment]
> Another idea ...
> which I think is based on how FormField + TextInput work ...
> is to do this via an explicit property.
> FormField and TextInput use `focusIndicator`.
> So, we could have FormField do what it does at line 192 in a way that effects a contained CheckBox.

I will check that out. Thanks for the suggestion.

**Comment by halocline** [comment]
Approach 3: https://github.com/grommet/grommet/pull/4930

**Comment by halocline** [comment]
> Approach 3: [grommet/grommet#4930](https://github.com/grommet/grommet/pull/4930)

Adopting approach 3 and have resolution on backwards compatibility questions represented in this issue https://github.com/grommet/grommet/issues/4947
