### ISSUE TITLE
npm install grommet-theme-hpe --save throws error

### ISSUE THREAD

**Issue by sathishiva** [grommet/grommet-theme-hpe#160]
**Version from my machine:**
node version: 15.0.1
npm version: 7.0.3
react-scripts: 4.0.2

**Log:**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ccs-ui-components@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from grommet-theme-hpe@2.0.2
npm ERR! node_modules/grommet-theme-hpe
npm ERR!   grommet-theme-hpe@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by halocline** [comment]
Can you try `npm install --legacy-peer-deps` as suggested 3rd line from bottom of the log?

**Comment by ShimiSun** [comment]
Adding to @halocline, you might find the generic description of the problem and the way to troubleshoot it on https://stackoverflow.com/questions/64573177/unable-to-resolve-dependency-tree-error-when-installing-npm-packages

**Comment by halocline** [comment]
Yes, my apologies for not providing additional detail for reference.  NPM v7 made the decision to "always run with --legacy-peer-deps set to false, so that missing peer dependencies will be highlighted when looking at the package tree." This differed from how NPM handled v4-6. Here is [NPM's blog post](https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major) discussing v7 changes.

**Comment by sathishiva** [comment]
Thanks @ShimiSun @halocline for the quick and detailed explanation!
It works with `npm install grommet-theme-hpe  --legacy-peer-deps`

**Comment by sathishiva** [comment]
If we have to run the `npm install` in CI. This won't work. Noticed that hpe package JSON using react version with ^. It has to be similar to grommet package.json (using     "react": ">= 16.6.1")
https://github.com/grommet/grommet/blob/master/package.json#L47
https://github.com/grommet/grommet-theme-hpe/blob/master/package.json#L25

**Comment by mukarramgit** [comment]
hi

can please tell me how to install a themeforest theme to react js and use it
