### ISSUE TITLE
Release grommet-theme-hpe 2.0.3 for access to updated button sizes, heading colors, tab styling, required field markings, layer rounding

### ISSUE THREAD

**Issue by halocline** [grommet/grommet-theme-hpe#162]
Are we comfortable releasing a patch for the HPE theme which would include the items listed below?

**Release Notes - DRAFT**

- Fixed ButtonKind sizes to reflect desired dimensions across sizes and kinds (e.g. primary, secondary, etc.). Enables ability to accommodate proposal for a greater variety of button sizes. 
- Added * (asterisk) to `required` FormField for clear identification and improved accessibility.
- Added `intelligentRounding` to Layer, allowing for layers to present flush against window edges.
- Fixed Layer default `border-radius`.
- Fixed Layer default elevation to be `large`.
- Added Card default elevation of `medium`.
- Added validation colors for `validation-ok` and `validation-warning`.
- Changed Heading `font-color` to be `text-strong` for greater emphasis and scan-ability.
- Changed Tab `active` styling to provide greater visual differentiation.
- Added Tip default styling.

**Comment by ShimiSun** [comment]
Sure, I was waiting to see if there is any critical feedback from the grommet release before releasing the theme, and I think it is safe to proceed with it.
Would you be able to write the release notes for this release?

**Comment by halocline** [comment]
> Would you be able to write the release notes for this release? From the above, it looks like you are halfway there.

I'd be happy to.

**Comment by MikeKingdom** [comment]
Note that the button size PR (theme half) isn't merged yet although I would think it could be. Eric approved so far...

**Comment by halocline** [comment]
Thanks for calling that out @MikeKingdom. I had/have 👀 on it!

**Comment by ericsoderberghp** [comment]
I would like to include https://github.com/grommet/hpe-design-system/issues/1409 in the next theme release as well.

**Comment by ShimiSun** [comment]
Button sizes PR is merged, thanks for the friendly reminder.

**Comment by ShimiSun** [comment]
`grommet-theme-hpe` 2.0.3 is released!
