### ISSUE TITLE
Checkbox in selectable DataTable does not show focus indicator when checkbox has focus

### ISSUE THREAD

**Issue by mgh5** [grommet/grommet-theme-hpe#166]
Checkbox in selectable DataTable does not show focus indicator when checkbox has focus

hpe theme's checkBox > check > extend is setting box-shadow to none causing this issue.
"grommet-theme-hpe": "^2.0.0"

**Comment by ShimiSun** [comment]
Related to #151

**Comment by britt6612** [comment]
This was fixed with  https://github.com/grommet/grommet/pull/5288
as well as here where the `box-shadow: none` was taken out  https://github.com/grommet/grommet-theme-hpe/pull/196/files
