### ISSUE TITLE
FormField + Select + focus

### ISSUE THREAD

**Issue by abbyperez** [grommet/grommet-theme-hpe#171]
Double focus issue for formfield and select. 

In the screenshot below, you can see two different focus areas. The expectation would be that there will only be one focus and it will be based on which component the user is currently using. In this case, I believe it would be the search box.

![Screen Shot 2021-03-01 at 2 30 53 PM](https://user-images.githubusercontent.com/74273299/109844428-58b8fb80-7c09-11eb-97a1-004f2e8d5042.png)

**Comment by ShimiSun** [comment]
I don't see the issue on Grommet itself, so I suspect this bug results from the HPE theme but it needs to be triage to double-check - let's prioritize this issue high on the backlog.

**Comment by britt6612** [comment]
So this is happening in Grommet. The `formfield` focus is just covered up by the select component. When I moved the `select` down a little you can see that both focuses are indeed there. Now this is only happening when `select` is being wrapped in `formfield` 

<img width="352" alt="Screen Shot 2021-03-16 at 9 44 30 PM" src="https://user-images.githubusercontent.com/42451602/111411791-cc92e380-86a0-11eb-83bc-4933d135eca7.png">
