### ISSUE TITLE
HPE Theme - 2.1.0 Release 

### ISSUE THREAD

**Issue by MikeWalrath** [grommet/grommet-theme-hpe#181]

**Comment by taysea** [comment]
DRAFT OF RELEASE NOTES: (pending decision to leave or revert Layer/Drop zindex changes)

- Fixed `menu.drop.align` to be `{{top: ‘bottom’, left: ‘left’}}`
- Added Pagination styling
- Added Spinner styling
- Fixed Drop margin with `drop.intelligentMargin` to allow Drop-reliant components like Tip to align properly
