### ISSUE TITLE
Will the Grommet theme font paths be the same after update or version changes

### ISSUE THREAD

**Issue by AkshayRangnekar8** [grommet/grommet-theme-hpe#211]
I am using the grommet metric hpe font paths directly in my application. I am downloading these fonts and then using them in my app.
Font paths like the ones mentioned below are used by me:
https://d3hq6blov2iije.cloudfront.net/fonts/HPEXS-Metric-Fonts/MetricHPEXS-Regular.woff2
https://d3hq6blov2iije.cloudfront.net/fonts/HPEXS-Metric-Fonts/MetricHPEXS-Regular.woff
https://d3hq6blov2iije.cloudfront.net/fonts/HPEXS-Metric-Fonts/MetricHPEXS-Bold.woff2
https://d3hq6blov2iije.cloudfront.net/fonts/HPEXS-Metric-Fonts/MetricHPEXS-Bold.woff

Can you please confirm if these font paths will be the same in future even after update or version changes?

**Comment by halocline** [comment]
Confirmed. These paths will be valid regardless of updates or version changes.
