### ISSUE TITLE
how to install themeforest theme to react js

### ISSUE THREAD

**Issue by mukarramgit** [grommet/grommet-theme-hpe#254]
can any one please tell me how to install the themeforest theme on react js and use it full demo

**Comment by mukarramgit** [comment]
> Hi @mukarramgit I'm not aware of a themeforest theme. If you are looking for instructions on how to include and use `grommet-theme-hpe` checkout the [readme](https://github.com/grommet/grommet-theme-hpe/blob/master/README.md) page for this repository

thank you

**Comment by jcfilben** [comment]
Closing this ticket. Feel free to reach out if there are additional questions/issues
