### ISSUE TITLE
Unselected toggle has severe contrast issues and doesn't look like a toggle

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-theme-hpe#29]
![image](https://user-images.githubusercontent.com/17883783/78184450-c0c5f700-7426-11ea-9c10-fd02e80e6c9d.png)

**Comment by ShimiSun** [comment]
Thanks for reporting, verfied on a sandbox https://codesandbox.io/s/hpe-theme-checkbox-hgepk
There is an ongoing effort on Checkbox design https://github.com/hpe-design/design-system/issues/514, it should account for this issue.

**Comment by taysea** [comment]
Closing this issue as the styling for toggle has been updated to fix contrast/readability issues.
