### ISSUE TITLE
How to change the border color as overloading into the React app?

### ISSUE THREAD

**Issue by biapar** [grommet/grommet-theme-hpe#296]
How to change the border color as overloading into the React app?

**Comment by biapar** [comment]
Here is the solution https://developer.hpe.com/blog/dark-mode-theming-in-grommet-theme-color-customization/

const gwtheme = deepMerge(hpe, gw);

**Comment by jcfilben** [comment]
Glad you found a solution to your question! Going to mark this as closed.
