### ISSUE TITLE
HPE specific components

### ISSUE THREAD

**Issue by karatechops** [grommet/grommet-theme-hpe#3]
I'm curious to hear the team's thoughts regarding HPE specific components being exported from the grommet theme package? Specifically, branded primary buttons. Currently V2 only allows general theming of a button which will cascade throughout various components. Without passing text to a button like `<Button><Text weight="bold">my button</Text></Button>` a user can't achieve properly branded HPE buttons.  

A pattern we could introduce to alleviate some verbosity and ensure brand consistency across applications is -
```
import { BrandButton } from 'grommet-hpe-theme';

<BrandButton label="my button" />
```

If we agree to do this my first question is - what is the best approach for implementation? Could grommet act as a peer dependency to this library? Or would it make more sense to add a Grommet dependency / StoryBook setup to this project?

Perhaps it's best to separate this idea out to a separate project - like `grommet-hpe-kit` which would provide utility like -
 
```
import { theme, BrandButton } from 'grommet-hpe-kit'
```

Just throwing some spaghetti against the wall to see what sticks 
# 🍝

**Comment by ericsoderberghp** [comment]
For the HPE brand buttons, I would expect `grommet-theme-hpe` to be capable of providing that. If it can't, then grommet and grommet-theme-hpe should be updated.
