### ISSUE TITLE
Dark mode contrast suffers when Night Shift / Night Light is enabled

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-theme-hpe#30]
Because most of the contrast difference between background-front and background-back in dark mode is in the blue channel, there is often no visible contrast difference when night mode is enabled and the blue channel largely disappears.

The following image is from a card grid with cards having background-front and the grid background having background-back.  View this image with Night Shift / Night Light enabled at different intensities.

![image](https://user-images.githubusercontent.com/17883783/78186596-38495580-742a-11ea-925e-a98fe6554c6f.png)

**Comment by gregfuruiye** [comment]
This issue has been addressed by using an updated color for background-front to #354050. I've also tested in Night Shift at different temperature settings. It is currently specified in our Figma color palette, needs to be updated in the theme. https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/hpe-color?node-id=9%3A28

**Comment by ShimiSun** [comment]
Merged, thanks @gregfuruiye !

**Comment by jcfilben** [comment]
Closing, looks like this was fixed by #35
