### ISSUE TITLE
Brand refresh - FileInput should receive updated button styling

### ISSUE THREAD

**Issue by halocline** [grommet/grommet-theme-hpe#313]
![Screenshot 2023-02-07 at 4 27 53 PM](https://user-images.githubusercontent.com/1756948/217390242-2b4fd2a7-cdff-4141-9538-1047063a0e5c.png)

I believe the remove button should be fully rounded. 

Audit other FileInput states for typography and button alignment to brand refresh direction.

**Comment by taysea** [comment]
Closing this issue since this has been resolved on NEXT.

<img width="435" alt="Screen Shot 2023-03-17 at 3 29 34 PM" src="https://user-images.githubusercontent.com/12522275/226063845-5e2d4d94-0aaa-449d-a681-944450687de0.png">
