### ISSUE TITLE
Brand Refresh - Write migration guide

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-theme-hpe#318]
Write migration guide for v4 to v5 of grommet-theme-hpe

## Acceptance Criteria

- [x] Published wiki page on this repo with migration guide

## Key Content

- [x] Details of all theme changes
- [x] Explanation on any manual changes needed in code to make it easy for teams to upgrade

**Comment by taysea** [comment]
WIP, let me know if you need access: https://docs.google.com/document/d/1hQqjxpeDb1HLRHVsk5dJvOAwsAEkoaNM2tp9Xh5atmE/edit?usp=sharing

**Comment by halocline** [comment]
Status 3/3/2023 - Reviewing and writing in parallel with answering some brand audit related questions. Major points are being hit; in refining/clarifying mode.

**Comment by taysea** [comment]
Migration guide has been published: https://github.com/grommet/grommet-theme-hpe/wiki/Migrating-from-HPE-Theme-4.x-to-5.x

Final item is to update link to release notes once theme has been published.
