### ISSUE TITLE
DataTable - units are not an accessible color

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet-theme-hpe#326]
- check with Keeth on color
- update theme
- update Figma to align

The color used for units in DataTable does not pass accessibility requirements

https://storybook.grommet.io/?path=/story/visualizations-datatable-units--units-data-table&globals=theme:hpe

<img width="1252" alt="Screen Shot 2023-03-10 at 11 01 40 AM" src="https://user-images.githubusercontent.com/54560994/224393881-6411f5de-7aa8-450e-a712-55f841263e65.png">

**Comment by taysea** [comment]
Friday 3/31:
- I tagged Keeth on a comment in Figma to confirm the color of choice. Waiting on a reply.

**Comment by Keeth-HPe** [comment]
@taysea  

I agree "text-weak" is a better option in terms of accessibility. I will change it in Figma, as I'm working on refactoring the component.
