### ISSUE TITLE
Design Tokens - Build step to resolve token values

### ISSUE THREAD

**Issue by taysea** [grommet/grommet-theme-hpe#353]
It would be ideal for the build step of grommet-theme-hpe to resolve the token values so callers don't need to add grommet-theme-hpe and hpe-design-tokens as dependencies in their projects.

**Comment by ericsoderberghp** [comment]
Upon further thought, I don't think callers will need to add hpe-design-tokens. grommet-theme-hpe can include hpe-design-tokens as a dependency and that should be enough. I have verified this with grommet-exp-vite stack.
