### ISSUE TITLE
Tag - Update medium tag in HPE theme

### ISSUE THREAD

**Issue by vavalos5** [grommet/grommet-theme-hpe#354]
Please update the medium tag in the HPE theme to the following:

height = 36px
top/bottom pad = 5px

Reasoning is to align with the medium button in the theme and consistency. Also, since tags can act like buttons, it would be good to keep those aligned.

I've included [Figma link](https://www.figma.com/file/8zrInotU4JK9LWP4WyZy25/branch/6zm1BmLxS90IEDwRoWPaPE/HPE-Design-System-Tags?node-id=8%3A56&t=MZBFrP0SgiSdoaKM-1) for reference

**Comment by halocline** [comment]
Closed by #355
