### ISSUE TITLE
Add support for styled-components v6 so it can be used with TypeScript

### ISSUE THREAD

**Issue by Lance-DC** [grommet/grommet-theme-hpe#389]
Current dependency is v5.

**Comment by jcfilben** [comment]
Hi @Lance-DC support for styled-components v6 is coming soon! This work can be tracked here: https://github.com/grommet/grommet/pull/7165

**Comment by LanceTaylor-HPE** [comment]
I see this was added in PR#397. Thanks!

**Comment by jcfilben** [comment]
No problem! Let us know if you run into any issues using styled components v6 with the latest version of Grommet. I'm going to mark this issue as closed for now.
