### ISSUE TITLE
Tab Selector

### ISSUE THREAD

**Issue by jweb5** [grommet/grommet-theme-hpe#4]
[05-19 (OneSphere Catalog Study Findings) (dragged).pdf](https://github.com/grommet/grommet-theme-hpe/files/3055490/05-19.OneSphere.Catalog.Study.Findings.dragged.pdf)

See attached excerpt from Melissa's report

**Comment by LiveFreeAndRoam** [comment]
HPE theme 1.0.0.

The selected `Tab` is barely distinguishable from other tabs.

See my codesandbox for an example: https://codesandbox.io/s/toggle-theme-tabs-1mb7s

### HPE Theme
![image](https://user-images.githubusercontent.com/8231064/76047041-4e8bff00-5fad-11ea-823f-9cede77bda15.png)

### Default Grommet Theme
![image](https://user-images.githubusercontent.com/8231064/76047083-74190880-5fad-11ea-9abe-ee004859ad2d.png)

**Comment by taysea** [comment]
Closing this ticket since tab styling has been updated in v5.
