### ISSUE TITLE
How to get theme without dependency on amazonaws?

### ISSUE THREAD

**Issue by blakehilliard** [grommet/grommet-theme-hpe#5]
If someone needs to use this theme in a tightly controlled internal network without access to https://hpefonts.s3.amazonaws.com, it will fail to retrieve the font "woff" files. What is the recommended way to get the theme with the font files already included? We could directly add the files we want and patch the theme's index.js to point to local font files, but I'm wondering if there's a more general solution for this scenario for grommet themes in general.

**Comment by karatechops** [comment]
Hi @blakehilliard, this is an interesting question. There may be a few work arounds but the easiest may be creating a custom theme based off the HPE theme. With this approach your HPE theme will stay version controlled and up-to-date.

```javascript
import { hpe } from 'grommet-theme-hpe';
import { deepMerge } from 'grommet/utils';
import { Grommet } from 'grommet';

const theme = deepMerge(hpe, {
  global: {
    font: {
      family: "'Metric', Arial, sans-serif",
      face: `
        @font-face {
          font-family: "Metric";
          src: url("/public/MetricHPE-Web-Regular.woff") format('woff');
        }
        @font-face {
          font-family: "Metric";
          src: url("/public/MetricHPE-Web-Bold.woff") format('woff');
          font-weight: 700;
        }
        @font-face {
          font-family: "Metric";
          src: url("/public/web/MetricHPE-Web-Semibold.woff") format('woff');
          font-weight: 600;
        }
        @font-face {
          font-family: "Metric";
          src: url("/public/MetricHPE-Web-Light.woff") format('woff');
          font-weight: 100;
        }
      `,
    },
  },
});

export const MyApp = () => <Grommet theme={theme}></Grommet>;
```

In this approach we assume you have a static assets directory in your web app titled `/public` that is serving the `.woff` files. You can find the font file links in the [src](https://github.com/grommet/grommet-theme-hpe/blob/master/src/js/index.js#L44-L66).

If you do not have a static assets directory in your app you could take a more advanced approach by base64ing the fonts and putting the output directly in the `src` field of the `@font-face` definition.

**Comment by Mohtashim-Sonasoft** [comment]
Yes! this link help me partially. Whenever I had to use global--> font--> family and face both keys and values so it was not working while I had use only family key and value here and font-face defined in my main.css file so its work properly.

Thanks for your response.

**Comment by Mohtashim-Sonasoft** [comment]
This is my theme.js file
![image](https://user-images.githubusercontent.com/50501142/58229187-71189880-7d4a-11e9-93ed-2c060e13b630.png)

and this one is my main.css file

![image](https://user-images.githubusercontent.com/50501142/58229251-9c02ec80-7d4a-11e9-9cbb-98024282ed42.png)

while I am using this way my font works properly. 
Thanks!

**Comment by karatechops** [comment]
Looks like you're good to go. Let us know if you have any other questions!
