### ISSUE TITLE
New color palette?

### ISSUE THREAD

**Issue by coltonw** [grommet/grommet-theme-hpe#6]
Is there a plan to update this theme to use the updated HPE color palette?

**Comment by ShimiSun** [comment]
Hi there, Grommet is using the grommet theme.
If you'd like to use the HPE theme you can find it here https://github.com/grommet/grommet-theme-hpe.
For example on how it can be consumed, you can check out this project https://github.com/ShimiSun/grommet-swarm

Let me know if you have further questions.

**Comment by ShimiSun** [comment]
Thanks for raising the issue. I'm taking a look at this now.

**Comment by ShimiSun** [comment]
Hi @coltonw thank you for filing an issue. we will be updating the hpe pallet as part of the effort that will result from this proposal https://github.com/grommet/grommet/issues/3452.
Thank you for your patient.

**Comment by johnny1K** [comment]
@ShimiSun do you have any update on this?

**Comment by ShimiSun** [comment]
Yes, I want to say it will be ready towards the end of the week, thank you for your patient.
@ericsoderberghp

**Comment by ShimiSun** [comment]
Fixed an available on ^1.0.0.
