### ISSUE TITLE
Buttons no longer match DS figma - text is not bold

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-theme-hpe#80]
Figma shows that primary and secondary buttons should have bold text styling, but this is what I am seeing:
![image](https://user-images.githubusercontent.com/17883783/85039855-61ce6f00-b145-11ea-81b7-9c2dd1b94544.png)

**Comment by ecircenis** [comment]
This is on windows, using grommet designer and latest theme.

**Comment by halocline** [comment]
@ecircenis The font weights for Primary and Secondary buttons have been corrected. Please let us know if you see otherwise.

**Comment by yzalvov** [comment]
@ecircenis I see otherwise with `"grommet": "^2.14.0"`

**Comment by britt6612** [comment]
@yzalvov are you referring to the weight of the font that you see ? in` "grommet": "^2.14.0"`

**Comment by yzalvov** [comment]
@britt6612 exactly.
