### ISSUE TITLE
Dsiabled Buttons respond to mouse over when hoverIndicator set 

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet-theme-hpe#93]
I cannot reproduce this using released versions.  Relevant version information from my `package.json`:

```
    "grommet": "https://github.com/grommet/grommet/tarball/stable",
    "grommet-icons": "^4.4.0",
    "grommet-theme-hpe": "https://github.com/grommet/grommet-theme-hpe/tarball/NEXT-stable",
```

`<Button disabled hoverIndicator label="Hover over me" />`

When a disable Button has hoverIndicator, it still responds to mouse over.

I wonder if the grommet-theme-hpe, (or maybe grommet), should check for disabled and also remove the hover attribute?

My thought here is that when a disabled Button reacts to mouse movement, it feels like the Button is not entirely disabled... it encourages me to click on it.  Then I wonder did the click do something or not!? 🤔

**Comment by ShimiSun** [comment]
I just wanted to double-check and confirm this issue is reproducible for a 'kind' button, and I'm not sure it's reproducible for any type the regular button. 
To know whether you are using the kind button, you should have `button.default` defined on your theme.
If the theme you are using is `"grommet-theme-hpe": "https://github.com/grommet/grommet-theme-hpe/tarball/NEXT-stable"` then it means that you are using the kind Button indeed. Just double-checking or giving points of thought for the next phase of the investigation.

**Comment by halocline** [comment]
I took a quick look last night the cursor treatment is proper and remains as `default`.  When `hoverIndicator` is present, the background gets active styling. The disabled state background color is actually an opacity value, so it is allowing the hoverIndicator active state "leak through" and seem interactive.

And in grommet-theme-hpe, we have background transparent: https://github.com/grommet/grommet-theme-hpe/blob/1f59e56c301b3f61ac915cc20f9b4dfafa6aef36/src/js/index.js#L325

The theme does not currently have `button.disabled.[kind].background` defined, only the general transparent background and opacity.

This is where the disabled style is being set, right after hoverIndicator style.
https://github.com/grommet/grommet/blob/8b64e810b42b2f69e332f4c18018d2d94d333e65/src/js/components/Button/StyledButtonKind.js#L253

It seems like we might want to change this line something like this... 
```
props.disabled && props.theme.button.disabled.background && disabledStyle(props.theme.button.disabled.opacity)
```

HOWEVER, we can't assume which kind of button variant it is, so we would need to check for all possible kinds
```
props.disabled && props.primary && props.theme.button.disabled.primary.background && disabledStyle(props.theme.button.disabled.opacity)
props.disabled && props.secondary && props.theme.button.secondary.background && disabledStyle(props.theme.button.disabled.opacity)
```

This isn't perfect, but communicates the direction of my thoughts.

**Comment by ShimiSun** [comment]
I think we are safe closing this issue, as the issue was fixed on the grommet core. Let us know if you have further questions.
