### ISSUE TITLE
Need more contrast between active and inactive buttons

### ISSUE THREAD

**Issue by RobertGary1** [grommet/grommet-theme-hpe#95]
It can be hard to tell the difference.

![image](https://user-images.githubusercontent.com/3485567/90073506-303dd400-dcae-11ea-8273-6fb4f446575d.png)

https://codesandbox.io/s/tender-mountain-xys64?initialpath=/Button&module=%2Fsrc%2FButton.js

**Comment by ShimiSun** [comment]
I think this issue is addressed on the next release of the hpe-theme aka (design-system theme)
https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=1%3A2

**Comment by RobertGary1** [comment]
@ShimiSun when will that updated theme be available? Will I be able to just update my grommet-theme-hpe library?

**Comment by ShimiSun** [comment]
Thanks for asking, the theme is not officially released yet to be used in production, but we do encourage teams to be up to date with the latest and greatest that is available on the design system and we'll release as soon as we'll cover the theme for all the components that will be documented on the DS (near future).
For using it, you can set your package.json to point to the [theme stable branch](https://github.com/grommet/grommet-theme-hpe#stable), here is a [package.json example](https://github.com/hpe-design/design-system/blob/20157dc500c6c2fb784db46c610cc2b0883e16d3/aries-site/package.json#L14) that is using it for reference.

Please be mindful that the new theme will have breaking changes as many hpe-brand requirements and design had changed, so some colors may not be available anymore and some components will change there styling.

We'll be working on a [migration guide](https://github.com/grommet/grommet-theme-hpe/wiki/Migration-guide-to-the-design-system-theme) to document the differences one may encounter.

**Comment by taysea** [comment]
Closing this ticket for inactivity and because styles have been updated since the creation of this ticket. Generally, default/toolbar buttons are the kinds that receive an "active" state. The active state is clearly distinguished because default/toolbar buttons have no background by default and a persistent background of "active-background" when active. The latest styles can be consumed from grommet-theme-hpe v5.
