### ISSUE TITLE
Select looks same for disabled and enabled

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [grommet/grommet-theme-hpe#96]
See code at [CodeSandbox.io](https://codesandbox.io/s/select-enabled-vs-disabled-h1mtu?file=/src/App.js:0-810)

Here is a code extract that renders the page:

```
  const options = ["one", "two", "three"];
  ...
        <Select placeholder="Select an option" options={options} />
        <Select disabled placeholder="Select an option" options={options} />

```

This is only evident in the NEXT-stable.  Here's an extract from my package.json:

    "grommet": "https://github.com/grommet/grommet/tarball/stable",
    "grommet-theme-hpe": "https://github.com/grommet/grommet-theme-hpe/tarball/NEXT-stable",

Using NEXT-stable, one of these is disabled... but they look identical:

![image](https://user-images.githubusercontent.com/8231064/90086232-4eaed880-dd5d-11ea-954d-9dd510bb9f08.png)

Comparing this with the released versions, grommet-them-hpe@^1.0.5, see my [CodeSandbox.io](https://codesandbox.io/s/select-enabled-vs-disabled-h1mtu?file=/src/App.js:0-810).  You can clearly see the 2nd Select dropdown is disabled.

![image](https://user-images.githubusercontent.com/8231064/90086430-c11fb880-dd5d-11ea-8216-d684e495fe29.png)

**Comment by taysea** [comment]
Thanks @LiveFreeAndRoam, can you try this code block in your app and confirm that it solves the issue you're seeing? It may require you to apply a custom theme to test this locally:
```
import { css } from 'styled-components';

const myTheme = deepMerge(hpe, {
  select: {
    control: {
      extend: ({ disabled }) => css`
        ${disabled && 'opacity: 0.3;'}
      `,
    },
  },
});
...
<Grommet theme={myTheme}> 
...
```
I have tested locally and saw this outcome:

Without theme changes
<img width="260" alt="Screen Shot 2020-08-26 at 9 45 30 AM" src="https://user-images.githubusercontent.com/12522275/91332655-6173d500-e781-11ea-90b2-931cebd501b9.png">

With theme changes
<img width="258" alt="Screen Shot 2020-08-26 at 9 45 15 AM" src="https://user-images.githubusercontent.com/12522275/91332660-620c6b80-e781-11ea-84ef-5877d8781888.png">

**Comment by LiveFreeAndRoam** [comment]
G'day Taylor,

That fixes the issue!  Thank you!!

I notice one more thing that I think needs attention.  The disabled Select box still responds to mouse-over events.  E.g. my mouse icon changes from an "arrow" to a "pointing-finger" when I mouse-over the disabled Select.  This is different to a regular disabled Button, where the mouse does not change when I mouse-over it.

**Comment by taysea** [comment]
Great, thanks for noting that. I will take a look at that as well.
