### ISSUE TITLE
Issues with tarball/NEXT-stable

### ISSUE THREAD

**Issue by GautamSatish** [grommet/grommet-theme-hpe#99]
Hello,

I have been trying to install dependencies for grommet-site, grommet-server etc. and hitting the following error:
yarn install
`error https://github.com/grommet/grommet-theme-hpe/tarball/NEXT-stable: Integrity check failed for "grommet-theme-hpe" (computed integrity doesn't match our records, got "sha512-YzByZQ+HxfaK4zMXB6BwSR+rxVKNUvAqm7pxHNWGkHHDLezD4do2YvgPjxSfofmDjnfr9aKz+2YCw2vCa9nBjA== sha1-NB+3Fp2F+FKsnvTNohXZsmS5ZxY=")`

npm install:
```
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: grommet-theme-hpe@https://github.com/grommet/grommet-theme-hpe/tarball/NEXT-stable.
```
I was only able to complete installation by replacing 
`"grommet-theme-hpe": "https://github.com/grommet/grommet-theme-hpe/tarball/NEXT-stable", `
with
`"grommet-theme-hpe": "^1.0.5",`

Could this be related to my setup?

**Comment by halocline** [comment]
Hi @GautamSatish 👋. We need to clear Yarn's cache so that your install references the latest tarball instance. To do so:

```
rm -r node_modules/grommet-theme-hpe
rm yarn.lock
yarn cache clean
yarn
```

These steps should get you up and running.

**Comment by LiveFreeAndRoam** [comment]
See issue #78.

npm does not work when referencing a branch (like NEXT-stable) for grommet-theme-hpe.  You will have to switch to yarn.  

It would be great to see #78 fixed, as the switch to yarn is not free.  In my case, apart from some slight differences in commands, we had to install yarn on all of our build machines (requiring a coordinated global effort with sys admins and devs) and update Makefiles to work with yarn and debug a few little things.  It was a painful exercise.

**Comment by ShimiSun** [comment]
You need to look into how npm is loading the packages, I'm suspecting that since grommet stable is never loaded to npm then npm never finds it, while the `yarn` command is loading the package in a different fashion.
